### ISSUE TITLE
Cannot use in rails4?

### ISSUE THREAD

**Issue by Yangff** [Tretti/rails-bootstrap-helpers#3]
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails-bootstrap-helpers (>= 0) x86-mingw32 depends on
      rails (~> 3.2.11) x86-mingw32

```
rails (4.0.0)
```

**Comment by jacob-carlborg** [comment]
I think you should be able to use HEAD with Rails 4. It has `rails (>= 3.2.11)` as dependency. Add `gem "rails-bootstrap-helpers" github: "Tretti/rails-bootstrap-helpers"` to your Gemfile.

**Comment by Yangff** [comment]
thanks, it works well!
